export const IPC_CHANNELS = {
  selectWorkbook: 'workbook:select',
  readWorkbookRange: 'workbook:read-range',
  readWorkbookFormulas: 'workbook:read-formulas',
  recalcWorkbook: 'workbook:recalc',
  readWorkbookMedia: 'workbook:read-media',
  readPivotDefinition: 'workbook:read-pivot-definition',
  readLocalImage: 'shell:read-local-image',
  closeWorkbook: 'workbook:close',
  saveWorkbook: 'workbook:save',
  /** Crash-recovery copy of a dirty workbook, written under userData */
  writeWorkbookRecovery: 'workbook:write-recovery',
  autoRenameWorkbook: 'workbook:auto-rename',
  workbookRenamed: 'workbook:renamed',
  pendingEditsChanged: 'workbook:pending-edits',
  closeSaveRequest: 'workbook:close-save-request',
  closeSaveResult: 'workbook:close-save-result',
  exportPdf: 'workbook:export-pdf',
  openExternal: 'shell:open-external',
  menuAction: 'menu:action',
  aiGetSettings: 'ai:get-settings',
  aiGetPublicSettings: 'ai:settings:get-public',
  aiSetGlobalDefault: 'ai:settings:set-default',
  aiVerifyAndSaveProvider: 'ai:provider:verify-and-save',
  aiRemoveProviderKey: 'ai:provider:remove-key',
  aiListModels: 'ai:models:list',
  aiRefreshModels: 'ai:models:refresh',
  aiGetConversationRoute: 'ai:conversation:get-route',
  aiSetConversationRoute: 'ai:conversation:set-route',
  aiChat: 'ai:chat',
  aiStream: 'ai:stream',
  aiStreamCancel: 'ai:stream-cancel',
  aiStreamChunk: 'ai:stream-chunk',
  aiGskStatus: 'ai:gsk-status',
  aiGskLogin: 'ai:gsk-login',
  // Chat attachments (sheets: prefix — docs already registers global files:* in
  // the shell; avoids collisions)
  filesPick: 'sheets:files-pick',
  filesAdd: 'sheets:files-add',
  filesAddPastedImage: 'sheets:files-add-pasted-image',
  filesRead: 'sheets:files-read',
  filesReadImage: 'sheets:files-read-image',
} as const
